action:
  hdf5_selected_names: []
  lerobot_name: motor
  lerobot_names: []
cameras: {}
fps_used:
  test: 0
outlier_deletion: false
state:
  hdf5_selected_names: []
  lerobot_name: motor
  lerobot_names: []
