action:
  hdf5_selected_names:
  - actions
  lerobot_name: actions
  lerobot_names:
  - desired_ee_pos_0
  - desired_ee_pos_1
  - desired_ee_pos_2
  - desired_ee_pos_3
  - desired_ee_pos_4
  - desired_ee_pos_5
  - desired_ee_pos_6
  - desired_gripper_width_0
cameras:
  front_cam1:
    channels: 3
    height: 480
    name: obs/front_cam1
    width: 640
  front_cam2:
    channels: 3
    height: 480
    name: obs/front_cam2
    width: 640
  front_cam3:
    channels: 3
    height: 480
    name: obs/front_cam3
    width: 640
  gripper_camera:
    channels: 3
    height: 480
    name: obs/gripper_camera
    width: 640

state:
  hdf5_selected_names:
  - obs/joint_pos
  - obs/joint_vel
  - obs/joint_torques
  - obs/curr_ee_pos
  - obs/gripper_width
  - obs/ee_force
  - obs/ee_torque
  lerobot_name: state
  lerobot_names:
  - joint_pos_0
  - joint_pos_1
  - joint_pos_2
  - joint_pos_3
  - joint_pos_4
  - joint_pos_5
  - joint_pos_6
  - joint_vel_0
  - joint_vel_1
  - joint_vel_2
  - joint_vel_3
  - joint_vel_4
  - joint_vel_5
  - joint_vel_6
  - joint_torques_0
  - joint_torques_1
  - joint_torques_2
  - joint_torques_3
  - joint_torques_4
  - joint_torques_5
  - joint_torques_6
  - curr_ee_pos_0
  - curr_ee_pos_1
  - curr_ee_pos_2
  - curr_ee_pos_3
  - curr_ee_pos_4
  - curr_ee_pos_5
  - curr_ee_pos_6
  - gripper_width_0
  - ee_force_0
  - ee_force_1
  - ee_force_2
  - ee_torque_0
  - ee_torque_1
  - ee_torque_2

fps_used:
  one_bag: 30.2424290339152

outlier_deletion: true